<img src="/img/logo-uvt.png">
<form enctype="application/x-www-form-urlencoded" action="/user/login" method="post" id="login_form">                        
    <p>
        <label for="email_">Email</label>
        <input type="text" id="email_" name="email_" class="round full-width-input required" required/>
    </p>
    <p>
        <label for="password_">Password</label>
        <input type="password" id="password_" name="password_" class="round full-width-input" required/>
    </p>
    <p>
    <label for="remember" style="display: inline">Remember me</label>
        <input style="display: inline" type="checkbox" id="remember" name="remember"/>    
    </p>
    <input type="submit" value="Login" class="round blue ic-right-arrow effect2" />
</form>
